### ISSUE TITLE
增加 frontend CI 設定

### ISSUE THREAD

**Issue by ShadowSunCat** [Game-as-a-Service/uno-flip-java#10]
當有新 frontend code 的 commit push 回 main branch 時，就需要觸發 build & test，並在失敗時通知 push 的人。

這裡有新手教學 https://hackmd.io/@iD40lBm-QAqgh62DVHbjPA/rJim4nAvn

A.C.
1. 使用 github 的 action 建立屬於 frontend 的 workflow
2. 獨立給 frontend 使用的 yaml 檔 (檔名為 frontend.yml)
3. 需要包含 build 和 test 兩個動作
4. 只有 frontend 資料夾下的 code 變動 才需要觸發此 workflow
5. 觸發 action 的時機： 回 main branch、有人發出 pull request

**Comment by arealclimber** [comment]
- [ ] Set up test library `Jest`
- [ ] Add sample test under directory `./frontend/__test__`
- [ ] Set up GitHub Action to build and test when there's PR into main branch and files of frontend change
