### ISSUE TITLE
[backend] 流程開發 - 進入遊戲

### ISSUE THREAD

**Issue by ShadowSunCat** [Game-as-a-Service/uno-flip-java#11]
驗收測試需求: 
玩家 A 為第一位進入遊戲的玩家，進入成功後會收到成功的 Response 和廣播訊息。
玩家 B 為第二位進入遊戲的玩家，進入成功後收到成功的 Response 會包含同桌玩家的資訊。

A.C.
完成進入遊戲的接口，包含廣播訊息。

注意事項:
- 先不用儲存到 DB，三層式架構 (Controller + Service + Memory Cache Repo)
- 以 ATDD 的方式開發，所以 Controller 要有驗收測試的測項。
- 各個 class 要有自己的單元測試保護

**Comment by haohaotw** [comment]
@ShadowSunCat 

我剛剛大概看一下程式碼，目前我們廣播訊息是使用 SseEmitter 來實現的，SseEmitter 好像只能從服務端到客戶端單向發送，想詢問一下未來會有需求是要雙向溝通的嗎 ？

**Comment by ShadowSunCat** [comment]
> @ShadowSunCat 
> 
> 我剛剛大概看一下程式碼，目前我們廣播訊息是使用 SseEmitter 來實現的，SseEmitter 好像只能從服務端到客戶端單向發送，想詢問一下未來會有需求是要雙向溝通的嗎 ？
> 

廣播訊息就是要單向通知玩家用的，所以我才會選SSE，如果是雙向的話，目前規劃都是走 API。

**Comment by haohaotw** [comment]
@ShadowSunCat 
明白了～
