### ISSUE TITLE
初始化 backend 專案

### ISSUE THREAD

**Issue by ShadowSunCat** [Game-as-a-Service/uno-flip-java#2]
把 backend 專案的基本設定設置好，方便接下來直接動工寫 code!

**請建置在 backend 資料夾下**

A.C.
1. 使用 java 17
2. 使用 springboot 最新版，並且能夠啟動。
3. 使用 maven 管理專案

**Comment by ShadowSunCat** [comment]
springboot 專案初始化可以用官網提供的產生器

maven 設定
group: com.waterball.unoflip
artifact: uno-flip
name: uno-flip

**Comment by ankertim** [comment]
springboot 最新版是要用哪一個版本? 
 3.1.0 嗎?

**Comment by ankertim** [comment]
springboot 最新版是要用哪一個版本?
3.1.0 嗎?

**Comment by ShadowSunCat** [comment]
> springboot 最新版是要用哪一個版本? 3.1.0 嗎?

可以

**Comment by ankertim** [comment]
> springboot 專案初始化可以用官網提供的產生器
> 
> maven 設定 group: tw.waterballsa.gaas.unoflip artifact: uno-flip name: uno-flip

這樣設定會變成 package tw.waterballsa.gaas.unoflip.unoflip;
unoflip 會重複兩次，要把 group 的 unoflip 拿掉嗎，還是照舊?

**Comment by qrtt1** [comment]
package 只是用 maven 的 template 生出來長那個樣子，其實可以自己 refactor 改成喜歡的樣子。不用把 start.spring.io 生出來的照單全收 :D
