### ISSUE TITLE
初始化 frontend 專案

### ISSUE THREAD

**Issue by ShadowSunCat** [Game-as-a-Service/uno-flip-java#3]
把 frontend 專案的基本設定設置好，方便接下來直接動工寫 code!

**請建置在 frontend 資料夾下**

A.C.
請前端夥伴幫忙填寫

**Comment by arealclimber** [comment]
1. Framework: Next.js (with App router or Page router)
2. Language: Typescript
3. UI: TailwindCSS (with Chakra UI or Headless UI)

**Comment by arealclimber** [comment]
- [x] Next.js v13 with Typescript
- [x] TailwindCSS
- [x] Chakra UI
