### ISSUE TITLE
API 接口設計

### ISSUE THREAD

**Issue by ShadowSunCat** [Game-as-a-Service/uno-flip-java#6]
我先列出遊戲需要的接口規格，如有疑問、想補充、調整，都可以在這個 issue 討論。

詳細請看 https://kindly-verdict-328.notion.site/API-4db7a832a38849238ed5c0cba6c8ace5?pvs=4

**Comment by ankertim** [comment]
沒辦法看規格誒，需要權限。

**Comment by ShadowSunCat** [comment]
> 沒辦法看規格誒，需要權限。

抱歉現在才看到訊息，我已經更新聯結了
